Repository Team-ToArt/HiddenArtist-Service, pull requests merged in 2024-10, with the labels that each got.

#30 ⚒️ Fix: Gradle build Cache 설정 수정
  .github/workflows/backend-build.yml
  .github/workflows/backend-push.yml
Labels: fix

#36 ♻️ Refactor: Mentoring 관련 테스트 추가
  backend/src/main/java/com/hiddenartist/backend/domain/mentoring/controller/MentoringController.java
  backend/src/main/java/com/hiddenartist/backend/domain/mentoring/persistence/LockApplicationTime.java
  backend/src/main/java/com/hiddenartist/backend/domain/mentoring/persistence/MentoringApplication.java
  backend/src/main/java/com/hiddenartist/backend/domain/mentoring/service/MentoringService.java
  backend/src/main/java/com/hiddenartist/backend/global/aop/AopForTransaction.java
  backend/src/main/java/com/hiddenartist/backend/global/aop/CustomSpringELParser.java
  backend/src/main/java/com/hiddenartist/backend/global/aop/DistributedLock.java
  backend/src/main/java/com/hiddenartist/backend/global/aop/DistributedLockAop.java
  backend/src/main/java/com/hiddenartist/backend/global/aws/S3Service.java
  backend/src/main/java/com/hiddenartist/backend/global/redis/LockApplicationTimeClient.java
  backend/src/main/java/com/hiddenartist/backend/global/redis/RedisLockClient.java
  backend/src/main/java/com/hiddenartist/backend/global/redis/RedisLockFacade.java
  backend/src/test/java/com/hiddenartist/backend/domain/mentoring/persistence/repository/MentoringRepositoryTest.java
  backend/src/test/java/com/hiddenartist/backend/global/config/AbstractIntegrationTest.java
  backend/src/test/java/com/hiddenartist/backend/global/config/AbstractMySQLRepositoryTest.java
  backend/src/test/java/com/hiddenartist/backend/global/config/AbstractRedisTest.java
  backend/src/test/java/com/hiddenartist/backend/global/config/TestContainerSetup.java
  backend/src/test/java/com/hiddenartist/backend/global/config/TestRedisConfig.java
  backend/src/test/java/com/hiddenartist/backend/global/redis/RedisDistributeLockTest.java
  backend/src/test/java/com/hiddenartist/backend/global/redis/RedisLockClientTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/schema.sql
Labels: refactor

#39 🐛 Fix: Static Resource 경로 수정
  docker/nginx.conf
  frontend/nginx.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/public/image/logo_fix_w.png
  frontend/public/image/right-arrow.svg
  frontend/public/image/right-chevron.svg
  frontend/public/image/search_icon.svg
  frontend/src/App.jsx
  frontend/src/Header.jsx
  frontend/src/Home.jsx
Labels: fix

#40 ✨ Feature: 작가, 작품, 멘토링 UI 추가
  docker/docker-compose.app.yml
  docker/docker-compose.db.yml
  docker/nginx.conf
  frontend/index.html
  frontend/package-lock.json
  frontend/public/image/down-chevron.svg
  frontend/src/App.jsx
  frontend/src/Artist.jsx
  frontend/src/ArtistArtMore.jsx
  frontend/src/ArtistDetail.jsx
  frontend/src/Artworks.jsx
  frontend/src/ArtworksDetail.jsx
  frontend/src/ExhDetail.jsx
  frontend/src/Exhibition.jsx
  frontend/src/Header.jsx
  frontend/src/Home.jsx
  frontend/src/Mentoring.jsx
  frontend/src/assets/css/artist.css
  frontend/src/assets/css/artworks.css
  frontend/src/assets/css/exhibition.css
  frontend/src/assets/css/header.css
  frontend/src/assets/css/home.css
  frontend/src/assets/css/mentoring.css
Labels: feature
